apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: "mathesukkj/hello-go:v4"
          env:
            - name: NAME
              value: "matheus"
            - name: AGE
              value: "18"
